from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Loan(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, member_id=None, book_id=None, due_date=None, status=None):  # noqa: E501
        """Loan - a model defined in OpenAPI

        :param id: The id of this Loan.  # noqa: E501
        :type id: int
        :param member_id: The member_id of this Loan.  # noqa: E501
        :type member_id: int
        :param book_id: The book_id of this Loan.  # noqa: E501
        :type book_id: int
        :param due_date: The due_date of this Loan.  # noqa: E501
        :type due_date: date
        :param status: The status of this Loan.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'id': int,
            'member_id': int,
            'book_id': int,
            'due_date': date,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'member_id': 'memberId',
            'book_id': 'bookId',
            'due_date': 'dueDate',
            'status': 'status'
        }

        self._id = id
        self._member_id = member_id
        self._book_id = book_id
        self._due_date = due_date
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Loan':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Loan of this Loan.  # noqa: E501
        :rtype: Loan
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Loan.


        :return: The id of this Loan.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Loan.


        :param id: The id of this Loan.
        :type id: int
        """

        self._id = id

    @property
    def member_id(self) -> int:
        """Gets the member_id of this Loan.


        :return: The member_id of this Loan.
        :rtype: int
        """
        return self._member_id

    @member_id.setter
    def member_id(self, member_id: int):
        """Sets the member_id of this Loan.


        :param member_id: The member_id of this Loan.
        :type member_id: int
        """

        self._member_id = member_id

    @property
    def book_id(self) -> int:
        """Gets the book_id of this Loan.


        :return: The book_id of this Loan.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this Loan.


        :param book_id: The book_id of this Loan.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def due_date(self) -> date:
        """Gets the due_date of this Loan.


        :return: The due_date of this Loan.
        :rtype: date
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date: date):
        """Sets the due_date of this Loan.


        :param due_date: The due_date of this Loan.
        :type due_date: date
        """

        self._due_date = due_date

    @property
    def status(self) -> str:
        """Gets the status of this Loan.


        :return: The status of this Loan.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Loan.


        :param status: The status of this Loan.
        :type status: str
        """

        self._status = status
